name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          docker build -f docker/backend/Dockerfile \
            -t ${{ inputs.registry }}/${{ inputs.image_name }}:stg-$TAG .

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - run: doctl registry login --expiry-seconds 600

      - run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          docker push ${{ inputs.registry }}/${{ inputs.image_name }}:stg-$TAG
