name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image_name:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: docker/backend/Dockerfile
      context:
        required: false
        type: string
        default: .
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build container image
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo "Building with Dockerfile: ${{ inputs.dockerfile }}"
          echo "Context: ${{ inputs.context }}"
          docker build -f ${{ inputs.dockerfile }} \
            -t ${{ inputs.registry }}/${{ inputs.image_name }}:stg-$TAG \
            ${{ inputs.context }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to registry
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          docker push ${{ inputs.registry }}/${{ inputs.image_name }}:stg-$TAG
