name: Collect Commits

on:
  workflow_call:
    outputs:
      all_commits:
        description: "Danh sách commit đã format"
        value: ${{ jobs.build-commits-list.outputs.all_commits }}

jobs:
  build-commits-list:
    runs-on: ubuntu-latest
    outputs:
      all_commits: ${{ steps.collect.outputs.all_commits }}
    steps:
      - name: Collect commits
        id: collect
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            msgs=$(jq -r '.[] 
              | select(.message | startswith("Merge pull request") | not)
              | select(.message | contains("Release Pull Request") | not)
              | "- \(.id[0:7]) \(.message)"' <<< '${{ toJSON(github.event.commits) }}')
          else
            msgs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/commits" \
            | jq -r '.[] 
                | select(.commit.message | startswith("## 🚀 Release Pull Request") | not)
                | select(.commit.message | contains("Release Pull Request") | not)
                | "- \(.commit.message)"')
          fi

          {
            echo "all_commits<<EOF"
            echo "$msgs"
            echo "EOF"
          } >> $GITHUB_OUTPUT





