name: Setup SSH

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      proxy_host:
        required: false
        type: string
      proxy_port:
        required: false
        type: string
    secrets:
      USERNAME: { required: true }
      SSHKEY: { required: true }
      PASSPHRASE: { required: true }
      SSH_PRIVATE_KEY: { required: true }

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ inputs.host }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          proxy_host: ${{ inputs.proxy_host }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.SSHKEY }}
          proxy_port: ${{ inputs.proxy_port }}
          script: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
