name: Telegram Manual Approval

on:
  workflow_call:
    secrets:
      TELEGRAM_TOKEN:
        required: true
      TELEGRAM_TO:
        required: true

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: powerdot/telegram-manual-approval@main
        with:
          TELEGRAM_KEY: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
